export const languages = [
  ["JavaScript", "JS", "javascriptillä", "javascriptiä"],
  ["TypeScript", "TS", "typescriptillä", "typescriptiä"],
  "Python",
  ["Java", "Javaa", "Javalla", "Javasta"],
  "C#",
  "PHP",
  "Ruby",
  "C++",
  [
    "C",
    "Clang",
    "C-lang",
    "C-kieli",
    "!C tai CE",
    "!C kortti",
    "!C-kortti",
    "!osio C",
    "!C-Level",
    "!C-panel",
    "!OVTES C",
    "!C, Chemical",
    "!2 C",
    "!5 C",
    "!interview C",
  ],
  ["Golang", "Go-lang", "Golangia", "Go ohjelmistokehittäjä", "Golangiin"],
  "Rust",
  "Scala",
  "Kotlin",
  "Swift",
  "Objective-C",
  "Perl",
  "Haskell",
  "Clojure",
  "Erlang",
  "Elixir",
  "Dart",
  "Lua",
  "R",
  "Bash",
  "Shell",
  "PowerShell",
  ["Assembly", "ASM"],
  "MATLAB",
  ["Visual Basic", "VBA"],
  "COBOL",
  "Fortran",
  "Lisp",
  "Pascal",
  "Delphi",
  "LabVIEW",
  "Ada",
  "PL/SQL",
  "Prolog",
];
export const frameworks = [
  ["Node", "Node.js", "NodeJS"],
  ["React", "React.js", "ReactJS"],
  ["Vue", "Vue.js", "VueJS"],
  ["Angular", "Angular.js", "AngularJS"],
  ["Svelte", "Svelte.js", "SvelteJS"],
  ["NextJS", "Next.js"],
  ["Nuxt", "Nuxt.js", "NuxtJS"],
  ["Gatsby", "Gatsby.js", "GatsbyJS"],
  ["Ember", "Ember.js", "EmberJS"],
  ["Express", "ExpressJS", "Express.js"],
  ["Jupyter Notebook", "JupyterNotebook", "Jupyter"],
  "Gatsby",
  "Django",
  ["Ruby on Rails", "Rails"],
  "Flask",
  "Spring",
  "Laravel",
  "Symfony",
  ["ASP.NET", " ASP"],
  ".NET",
  ["Electron", "Electron.js", "ElectronJS"],
  ["Flutter", "Flutter.js", "FlutterJS"],
  ["React Native", "ReactNative", "React-Native"],
  ["Ionic", "Ionic.js", "IonicJS"],
  ["REST", "RESTful"],
  ["GraphQL", "Graph QL", "Graph-QL"],
  ["WordPress", "Word Press", "Word-Press"],
  ["Shopify", "Shopify.js", "ShopifyJS"],
  ["WooCommerce", "Woo Commerce", "Woo-Commerce"],
  ["Bootstrap", "Bootstrap.js", "BootstrapJS"],
  ["Tailwind", "Tailwind.js", "TailwindJS"],
  ["Unreal Engine", "UnrealEngine", "Unreal-Engine"],
  ["Unity", "Unity.js", "UnityJS"],
  ["TensorFlow", "Tensor Flow", "Tensor-Flow"],
  ["PyTorch", "Py Torch", "Py-Torch"],
  ["Keras", "Keras.js", "KerasJS"],
  ["Pandas", "Pandas.js", "PandasJS"],
  ["NumPy", "NumPy.js", "NumPyJS"],
  "FastAPI",
  "Jquery",
  ["ROS", "Robot Operating System"],
];
export const databases = [
  ["Relational databases", "SQL", "mySQL", "PostgreSQL", "SQLite"],
  ["NoSQL databases", "noSQL", "no-SQL", "MongoDB", "DynamoDB", "Redis", "Cassandra", "Neo4j"],
  ["Vector databases", "vectorDB", "vector-database", "vektori tietokannat", "vektori tietokanta"],
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "MariaDB",
  "MongoDB",
  "DynamoDB",
  "Redis",
  "Cassandra",
  "Microsoft SQL Server",
  "MS-SQL",
  "Oracle Database",
  "IBM Db2",
  "SAP HANA",
  "Teradata",
  "Neo4j",
  "ArangoDB",
  "Couchbase",
  "CouchDB",
];
export const cloud = [
  ["AWS", "Amazon Web Services", "S3 Bucket", "EC2"],
  ["Azure", "Microsoft Cloud"],
  ["Google Cloud", "GCP"],
  "Public cloud",
  ["Private cloud", "on premise"],
  "Hybrid cloud",
  "Digital Ocean",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Cloudflare",
  "Linode",
  "Rackspace",
  "IBM Cloud",
  "Alibaba Cloud",
  "Oracle Cloud",
  "VMware Cloud",
  "Red Hat Cloud",
  "Salesforce Cloud",
  "SAP Cloud",
  ["Cloud", "Pilvi", "pilvipalveluiden", "pilvipalvelu"],
];
export const devops = [
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "Bitbucket",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitLab CI/CD",
  "Ansible",
  "Vagrant",
  "Chef",
  "Puppet",
  "Docker",
  "Kubernetes",
  "Terraform",
  "AWS CloudFormation",
  "Nagios",
  "Splunk",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Nginx",
  "Agile",
  "Scrum",
  "Kanban",
  "CI/CD",
  "DevOps",
  "Pipeline",
  "Taiga",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  "Azure DevOps",
];
export const dataScience = [
  ["Machine Learning", "Koneoppiminen", "Koneoppimisen"],
  ["Deep Learning", "Syväoppiminen", "Syväoppimisen"],
  ["Reinforcement learning", "Vahvistuoppiminen", "Vahvistuoppimisen"],
  "Big Data",
  ["Data Analysis", "Data Analyst", "Data Analytics", "Data-analyysi", "Data-analyytikko", "Data-analytiikka"],
  ["Data Visualization", "Data Visualisation", "Data Visualisointi", "Data Visualisointi"],
  ["Data Engineering", "Data Engineer", "Data Engineering", "Data Engineer"],
  ["Natural Language Processing", "NLP", "Luonnollisen kielen käsittely", "Luonnollisen kielen käsittely"],
  ["Computer Vision", "konenäkö"],
  ["Statistics", "Statistical Analysis", "Tilastotiede", "Tilastollinen analyysi"],
  ["Business Intelligence", "Bussiness äly"],
  ["Data Warehousing", "Data Warehouse", "Data Warehousing", "Data Warehouse", "Datan varastointi"],
  ["Data pipelines", "Data pipeline"],
  ["Data Modeling", "Data Modelling", "Data Modeler", "Datan mallintaminen", "Datan mallintaja"],
  ["Data Mining", "Data Miner", "Datan kaivaminen", "Datan kaivaja"],
  ["Data Management", "Datan hallinta"],
  ["Artificial Intelligence", "Tekoäly", "Tekoälyt", "tekoäly", "tekoälyt"],
];
export const softSkills = [
  ["Communication", "Viestintä", "kommunikointi", "kommunikaaatio"],
  ["Teamwork", "Tiimityöskentely", "Collaboration", "Yhteistyö", "tiimityö", "team player"],
  ["Problem Solving", "Problem-solving", "Ongelmanratkaisu", "critical thinking", "problem solver"],
  ["Innovation", "Creativity", "Creative", "Luovuus", "Innova", "luova"],
  ["Time management", "Ajanhallinta", "prioritize", "priorisoi"],
  ["Adaptability", "Mukautuvuus", "sopeutuvuus", "sopeutumis"],
  ["Flexibility", "Joustavuus"],
  ["Leadership", "Johtajuus", "johtaminen", "johtaa", "tiimin vetäjä", "Team leading", "team leader"],
  ["People skills", "ihmisläheinen"],
  ["Work ethic", "Työmoraali"],
  ["Dedication", "Sitoutuminen"],
  ["Reliability", "Luotettavuus"],
  ["Optimism", "Positiivinen asenne", "Positive attitude", "Optimismi", "positiivinen", "positiivisuus"],
  ["Customer Service", "asiakaspalvelu", "asiakaspalveluhenki", "asiakaslähtöi"],
  ["Motivation", "motivaatio", "motivoitunut"],
  ["Empathy", "Empatia"],
  ["Patience", "Kärsivällisyys", "kärsivällinen"],
  ["Accountability", "Vastuullisuus", "vastuullinen"],
  ["Self-directed", "itsenäinen", "itseohjautuva"],
  ["Curiosity", "utelias"],
  ["Pressure Tolerance", "paineensietokyky", "paineensieto", "under pressure", "paineen alla"],
  ["Feedback", "palautetta", "palaute", "palautteen"],
];
export const positions = [
  ["Full Stack", "Full-Stack", "Fullstack"],
  ["Front End", "Front-End", "Frontend", "frontti"],
  ["Back End", "Back-End", "Backend", "bäkkäri"],
  ["Consultant", "Consulting", "Konsultti", "Konsultointi"],
  [
    "Software Developer",
    "Software Engineer",
    "SW Developer",
    "Ohjelmistokehittäjä",
    "Ohjelmoija",
    "Koodari",
    "Koodaaja",
    "Kehittäjä",
    "Developer",
  ],
  ["Software Architect", "Software Architecture", "Arkkitehti"],
  ["Web Developer", "Web Development", "web-kehitys", "web-kehittäjä"],
  ["Mobile Developer", "Mobile Development", "mobiilikehitys", "mobiilikehittäjä"],
  ["DevOps Engineer", "DevOps Developer", "CI-/DevOps"],
  ["Data Engineer", "Data Engineering"],
  ["Data Scientist", "Data Science", "Data Engineer"],
  ["Machine Learning Engineer", "Machine Learning"],
  ["Cloud Engineer", "Cloud Engineering"],
  ["Embedded", "Sulautetut"],
  ["Cyber Security", "Security Engineering", "Security Engineer", "Tietoturva", "Tietoturvakonsultti", "tietoturvan"],
  ["QA Engineer", "QA Engineering", "Test Engineer", "Test Engineering", "Testauksen"],
  ["UX Designer", "UX Design", "Käytettävyys", "Saavutettavuus"],
  ["UI Designer", "UI Design", "Käyttöliittymäsuunnittelija", "Käyttöliittymäsuunnittelu"],
  ["Designer", "Suunittelija"],
  ["System Administrator", "System Administration", "Järjestelmänvalvoja", "järjestelmävastaava"],
  ["System Specialist", "System Specialist", "Järjestelmäasiantuntija"],
  ["Product Manager", "Product Management", "Product Owner"],
  ["Project Manager", "Project Management"],
  ["Business Analyst", "Business Analysis"],
  ["Scrum Master"],
  ["AI Engineer", "Machine Learning Engineer", "AI Programmer", "Tekoäly", "AI Developer"],
  ["Blockchain Engineer", "Blockchain Developer", "Lohjoketju"],
  ["Game Developer", "Game Development", "Pelikehittäjä", "Pelikehitys"],
  ["Game Designer", "Game Design", "Pelisuunnittelija", "Pelisuunnittelu"],
  ["Test Automation", "Testausautomaatio"],
  ["Teacher / Professor", "Teacher", "Opettaja", "Professori"],
  ["Researcher", "Tutkija"],
  ["Salesman", "Myynti", "Myyjä"],
];
export const seniority = [
  ["Intern / Trainee", "Intern", "Trainee", "Harjoittelija", "harjoittelu", "digistar", "kesätyö"],
  ["Junior", "Juniori", "entry"],
  ["Senior", "Seniori", "senior"],
  ["Architect", "Arkkitehti"],
  ["Lead", "Tiimin vetäjä", "Johtava", "Johtaja"],
  ["Head", "Päälikkö", "Principal"],
  ["Product Owner", "Omistaja", "owner"],
  ["Executive", "Director", "Vice President", "Chief"],
];