export const languages = [
  ["JavaScript", "JS", "javascriptillä", "javascriptiä"],
  ["TypeScript", "TS", "typescriptillä", "typescriptiä"],
  ["Python", "Py"],
  ["Java", "Javaa", "Javalla", "Javasta"],
  ["C#", "C Sharp", "C-Sharp"],
  "PHP",
  "Ruby",
  ["C++", "C plus plus", "Cplusplus"],
  [
    "C",
    "Clang",
    "C-lang",
    "C-kieli",
    "!C tai CE",
    "!C kortti",
    "!C-kortti",
    "!osio C",
    "!C-Level",
    "!C-panel",
    "!OVTES C",
    "!C, Chemical",
    "!2 C",
    "!5 C",
    "!interview C",
    "!ISO C",
  ],
  ["Golang", "Go-lang", "Golangia", "Go ohjelmistokehittäjä", "Golangiin"],
  "Rust",
  "Scala",
  "Kotlin",
  "Swift",
  "Objective-C",
  "Perl",
  "Haskell",
  "Clojure",
  "Erlang",
  "Elixir",
  "Dart",
  "Lua",
  "R",
  ["Bash", "Bourne"],
  ["Shell", "Shell Script", "Shell-scripting"],
  "PowerShell",
  ["Assembly", "ASM"],
  "MATLAB",
  ["Visual Basic", "VBA"],
  "COBOL",
  "Fortran",
  "Lisp",
  "Pascal",
  "Delphi",
  "LabVIEW",
  "Ada",
  "PL/SQL",
  "Prolog",
  "Groovy",
  "F#",
  "OCaml",
  "Julia",
  "Crystal",
];
export const frameworks = [
  ["Node", "Node.js", "NodeJS"],
  ["React", "React.js", "ReactJS"],
  ["Vue", "Vue.js", "VueJS"],
  ["Angular", "Angular.js", "AngularJS"],
  ["Svelte", "Svelte.js", "SvelteJS"],
  ["Next.js", "NextJS", "Next"],
  ["Nuxt", "Nuxt.js", "NuxtJS"],
  ["Gatsby", "Gatsby.js", "GatsbyJS"],
  ["Ember", "Ember.js", "EmberJS"],
  ["Express", "ExpressJS", "Express.js"],
  ["NestJS", "Nest", "Nest.js"],
  ["Fastify", "Fastify.js"],
  ["Hapi", "hapi.js"],
  ["Koa", "Koa.js"],
  ["Remix", "Remix.run"],
  ["Astro", "Astro.js"],
  ["SolidJS", "Solid", "Solid.js"],
  ["Qwik", "Qwik.js"],
  ["Electron", "Electron.js", "ElectronJS"],
  ["Tauri", "Tauri App"],
  ["Jupyter Notebook", "JupyterNotebook", "Jupyter"],
  "Django",
  ["Ruby on Rails", "Rails"],
  "Flask",
  ["FastAPI", "Fast API"],
  "Spring",
  ["Spring Boot", "SpringBoot"],
  "Laravel",
  "Symfony",
  ["ASP.NET", "ASP", "ASP Net"],
  ".NET",
  ["Flutter", "Flutter.js", "FlutterJS"],
  ["React Native", "ReactNative", "React-Native", "RN"],
  ["Ionic", "Ionic.js", "IonicJS"],
  ["Expo", "Expo Go"],
  ["Serverless Framework", "Serverless"],
  ["REST", "RESTful"],
  ["GraphQL", "Graph QL", "Graph-QL"],
  ["tRPC", "TRPC"],
  ["gRPC", "grpc"],
  ["WordPress", "Word Press", "Word-Press"],
  ["Shopify", "Shopify.js", "ShopifyJS"],
  ["WooCommerce", "Woo Commerce", "Woo-Commerce"],
  ["Strapi", "Strapi CMS"],
  ["Contentful", "Contentful CMS"],
  ["Sanity", "Sanity CMS"],
  ["Bootstrap", "Bootstrap.js", "BootstrapJS"],
  ["Tailwind", "Tailwind.js", "TailwindCSS", "TailwindCSS"],
  ["Chakra UI", "ChakraUI"],
  ["MUI", "Material UI", "Material-UI"],
  ["Unreal Engine", "UnrealEngine", "Unreal-Engine"],
  ["Unity", "Unity.js", "Unity3D", "UnityJS"],
  ["TensorFlow", "Tensor Flow", "Tensor-Flow"],
  ["PyTorch", "Py Torch", "Py-Torch"],
  ["Keras", "Keras.js", "KerasJS"],
  ["Pandas", "Pandas.js", "PandasJS"],
  ["NumPy", "NumPy.js", "NumPyJS"],
  ["OpenCV", "Open CV"],
  ["ROS", "Robot Operating System"],
  ["Bun", "Bun.js"],
  ["Vitest", "Vite Test"],
  ["Vite", "Vite.js"],
];
export const databases = [
  ["Relational databases", "SQL", "MySQL", "PostgreSQL", "SQLite"],
  ["NoSQL databases", "NoSQL", "MongoDB", "DynamoDB", "Redis", "Cassandra", "Neo4j", "Couchbase"],
  ["Vector databases", "Vector DB", "vectorDB", "vector-database", "vektori tietokannat", "vektori tietokanta"],
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "MariaDB",
  "MongoDB",
  "DynamoDB",
  "Redis",
  "Cassandra",
  "Microsoft SQL Server",
  "MS-SQL",
  "Oracle Database",
  "IBM Db2",
  "SAP HANA",
  "Teradata",
  "Neo4j",
  "ArangoDB",
  "Couchbase",
  "CouchDB",
  "Elasticsearch",
  "OpenSearch",
  "ClickHouse",
  "Snowflake",
  "BigQuery",
  "DuckDB",
  "Firebolt",
  "Firestore",
  "Dgraph",
  "FaunaDB",
  "PlanetScale",
  "Supabase",
  "RDS",
  "Aurora",
  "Dolt",
  "InfluxDB",
  "TimescaleDB",
];
export const cloud = [
  ["AWS", "Amazon Web Services", "S3", "S3 Bucket", "EC2", "ECS", "EKS", "Lambda", "CloudFront"],
  ["Azure", "Microsoft Cloud", "Azure Cloud"],
  ["Google Cloud", "GCP", "Google Cloud Platform", "Cloud Run", "GKE"],
  ["DigitalOcean", "Digital Ocean"],
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Cloudflare",
  "Linode",
  "Rackspace",
  "IBM Cloud",
  "Alibaba Cloud",
  "Oracle Cloud",
  "VMware Cloud",
  "Red Hat Cloud",
  "Salesforce Cloud",
  "SAP Cloud",
  ["Public cloud", "Public Cloud"],
  ["Private cloud", "Private Cloud", "on premise", "on-premise", "onprem"],
  ["Hybrid cloud", "Hybrid Cloud"],
  ["Cloud", "Pilvi", "pilvipalveluiden", "pilvipalvelu"],
  ["Serverless", "Serverless Computing"],
  ["Edge Computing", "Edge"],
  ["Kubernetes", "K8s"],
  ["OpenShift", "RedHat OpenShift"],
];
export const devops = [
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "Bitbucket",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitLab CI/CD",
  "Ansible",
  "Vagrant",
  "Chef",
  "Puppet",
  "Docker",
  "Kubernetes",
  "Terraform",
  "AWS CloudFormation",
  "Helm",
  "ArgoCD",
  "FluxCD",
  "Prometheus",
  "Grafana",
  "Loki",
  "Tempo",
  "Jaeger",
  "OpenTelemetry",
  "Istio",
  "Linkerd",
  "Envoy",
  "Consul",
  "Vault",
  "Nagios",
  "Splunk",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "SonarQube",
  "Sentry",
  "Datadog",
  "New Relic",
  "PagerDuty",
  "OpsGenie",
  "Nginx",
  "Agile",
  "Scrum",
  "Kanban",
  "CI/CD",
  "DevOps",
  "GitOps",
  "Pipeline",
  "Taiga",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  "Azure DevOps",
  "Artifactory",
  "Nexus",
  "Harbor",
  "K6",
];
export const dataScience = [
  ["Machine Learning", "Koneoppiminen", "Koneoppimisen"],
  ["Deep Learning", "Syväoppiminen", "Syväoppimisen"],
  ["Reinforcement Learning", "Reinforcement learning", "Vahvistuoppiminen", "Vahvistuoppimisen"],
  "Big Data",
  ["Data Analysis", "Data Analyst", "Data Analytics", "Data-analyysi", "Data-analyytikko", "Data-analytiikka"],
  ["Data Visualization", "Data Visualisation", "Data Visualisointi"],
  ["Data Engineering", "Data Engineer"],
  ["Natural Language Processing", "NLP", "Luonnollisen kielen käsittely"],
  ["Computer Vision", "konenäkö"],
  ["Statistics", "Statistical Analysis", "Tilastotiede", "Tilastollinen analyysi"],
  ["Business Intelligence", "Business Intel", "Bussiness äly"],
  ["Data Warehousing", "Data Warehouse", "Datan varastointi"],
  ["Data Pipelines", "Data pipeline", "ETL", "ELT"],
  ["Data Modeling", "Data Modelling", "Data Modeler", "Datan mallintaminen", "Datan mallintaja"],
  ["Data Mining", "Data Miner", "Datan kaivaminen", "Datan kaivaja"],
  ["Data Management", "Datan hallinta"],
  ["Artificial Intelligence", "Tekoäly", "Tekoälyt", "AI"],
  ["Generative AI", "GenAI", "Gen AI", "Generatiivinen tekoäly"],
  ["Large Language Model", "Large Language Models", "LLM", "LLMs"],
  ["Foundation Model", "Foundation Models"],
  ["RAG", "Retrieval Augmented Generation"],
  ["Prompt Engineering", "Prompt Engineer"],
  ["MLOps", "ML Ops"],
  ["LLMOps", "LLM Ops"],
  ["Feature Store", "Feature Stores"],
  ["Data Lake", "Data Lakes"],
  ["Lakehouse", "Lake House"],
  ["Delta Lake", "DeltaLake"],
  ["Apache Spark", "Spark"],
  ["Apache Hadoop", "Hadoop"],
  ["Snowflake", "Snowflake DB"],
  ["Databricks", "Data Bricks"],
  ["Airflow", "Apache Airflow"],
  ["Kubeflow", "KubeFlow"],
  ["Vector Database", "Vector DB", "Vector Store"],
];
export const softSkills = [
  ["Communication", "Viestintä", "kommunikointi", "kommunikaaatio"],
  ["Teamwork", "Tiimityöskentely", "Collaboration", "Yhteistyö", "tiimityö", "team player"],
  ["Problem Solving", "Problem-solving", "Ongelmanratkaisu", "critical thinking", "problem solver"],
  ["Innovation", "Creativity", "Creative", "Luovuus", "Innova", "luova"],
  ["Time Management", "Time management", "Ajanhallinta", "prioritize", "priorisoi"],
  ["Adaptability", "Mukautuvuus", "sopeutuvuus", "sopeutumis"],
  ["Flexibility", "Joustavuus"],
  ["Leadership", "Johtajuus", "johtaminen", "johtaa", "tiimin vetäjä", "Team leading", "team leader"],
  ["People Skills", "People skills", "ihmisläheinen"],
  ["Work Ethic", "Work ethic", "Työmoraali"],
  ["Dedication", "Sitoutuminen"],
  ["Reliability", "Luotettavuus"],
  ["Optimism", "Positiivinen asenne", "Positive attitude", "Optimismi", "positiivinen", "positiivisuus"],
  ["Customer Service", "asiakaspalvelu", "asiakaspalveluhenki", "asiakaslähtöi"],
  ["Motivation", "motivaatio", "motivoitunut"],
  ["Empathy", "Empatia"],
  ["Patience", "Kärsivällisyys", "kärsivällinen"],
  ["Accountability", "Vastuullisuus", "vastuullinen"],
  ["Self-directed", "itsenäinen", "itseohjautuva"],
  ["Curiosity", "utelias"],
  ["Pressure Tolerance", "paineensietokyky", "paineensieto", "under pressure", "paineen alla"],
  ["Feedback", "palautetta", "palaute", "palautteen"],
  ["Mentoring", "Mentorointi", "Mentor"],
  ["Conflict Resolution", "Conflict Management"],
  ["Ownership", "Omistajuus"],
];
export const positions = [
  ["Full Stack", "Full-Stack", "Fullstack"],
  ["Front End", "Front-End", "Frontend", "frontti"],
  ["Back End", "Back-End", "Backend", "bäkkäri"],
  ["Consultant", "Consulting", "Konsultti", "Konsultointi"],
  [
    "Software Developer",
    "Software Engineer",
    "SW Developer",
    "Ohjelmistokehittäjä",
    "Ohjelmoija",
    "Koodari",
    "Koodaaja",
    "Kehittäjä",
    "Developer",
  ],
  ["Software Architect", "Software Architecture", "Arkkitehti"],
  ["Solutions Architect", "Solution Architect"],
  ["Enterprise Architect", "Enterprise Architecture"],
  ["Web Developer", "Web Development", "web-kehitys", "web-kehittäjä"],
  ["Mobile Developer", "Mobile Development", "mobiilikehitys", "mobiilikehittäjä"],
  ["DevOps Engineer", "DevOps Developer", "CI-/DevOps"],
  ["Platform Engineer", "Platform Engineering"],
  ["Site Reliability Engineer", "SRE", "Reliability Engineer"],
  ["Data Engineer", "Data Engineering"],
  ["Data Scientist", "Data Science"],
  ["Machine Learning Engineer", "Machine Learning"],
  ["MLOps Engineer", "ML Ops Engineer"],
  ["AI Engineer", "AI Programmer", "AI Developer"],
  ["Prompt Engineer", "Prompt Engineering"],
  ["Cloud Engineer", "Cloud Engineering"],
  ["Embedded", "Sulautetut"],
  ["Cyber Security", "Security Engineering", "Security Engineer", "Tietoturva", "Tietoturvakonsultti", "tietoturvan"],
  ["Security Analyst", "SecOps"],
  ["Application Security Engineer", "AppSec"],
  ["QA Engineer", "QA Engineering", "Test Engineer", "Test Engineering", "Testauksen"],
  ["Test Automation", "Testausautomaatio"],
  ["UX Designer", "UX Design", "Käytettävyys", "Saavutettavuus"],
  ["UI Designer", "UI Design", "Käyttöliittymäsuunnittelija", "Käyttöliittymäsuunnittelu"],
  ["Product Designer", "UX/UI Designer"],
  ["Designer", "Suunittelija"],
  ["System Administrator", "System Administration", "Järjestelmänvalvoja", "järjestelmävastaava"],
  ["System Specialist", "Järjestelmäasiantuntija"],
  ["Product Manager", "Product Management", "Product Owner"],
  ["Project Manager", "Project Management"],
  ["Business Analyst", "Business Analysis"],
  ["Data Platform Engineer", "Data Platform"],
  ["Scrum Master"],
  ["Blockchain Engineer", "Blockchain Developer", "Lohjoketju"],
  ["Game Developer", "Game Development", "Pelikehittäjä", "Pelikehitys"],
  ["Game Designer", "Game Design", "Pelisuunnittelija", "Pelisuunnittelu"],
  ["Teacher / Professor", "Teacher", "Opettaja", "Professori"],
  ["Researcher", "Tutkija"],
  ["Research Engineer", "Research Engineering"],
  ["Salesman", "Myynti", "Myyjä"],
  ["FinOps Engineer", "FinOps"],
  ["Observability Engineer", "Observability"],
];
export const seniority = [
  ["Intern / Trainee", "Intern", "Trainee", "Harjoittelija", "harjoittelu", "digistar", "kesätyö"],
  ["Junior", "Juniori", "entry", "Junior-level", "Junior level"],
  ["Mid", "Mid-level", "Mid level", "Intermediate"],
  ["Senior", "Seniori", "senior"],
  ["Staff", "Staff Engineer"],
  ["Principal", "Principal Engineer"],
  ["Architect", "Arkkitehti"],
  ["Lead", "Tiimin vetäjä", "Johtava", "Johtaja"],
  ["Head", "Päälikkö"],
  ["Product Owner", "Omistaja", "owner"],
  ["Executive", "Director", "Vice President", "Chief", "C-level"],
];
