/**
 * Improved keyword lists for classifying technologies from job descriptions.
 *
 * Conventions:
 * - Each item is either a string (single keyword) or an array of synonyms/variants.
 * - Items that begin with "!" are NEGATIVE keywords (contexts to exclude).
 * - Prefer lowercase/uppercase-insensitive matching in your classifier.
 * - Finnish variants are included where commonly seen.
 */

export const languages = [
  ["JavaScript", "JS", "Javascript", "javascriptillä", "javascriptiä", "ECMAScript", "ES6"],
  ["TypeScript", "TS", "Typescript", "TSX"],
  ["Python", "Py"],
  ["Java", "Javaa", "Javalla", "Javasta", "JVM"],
  ["C#", "C sharp", "C-sharp", "Csharp", ".NET C#"],
  ["PHP", "Php"],
  "Ruby",
  ["C++", "CPP", "C plus plus", "C-plus-plus"],
  [
    "C",
    "Clang",
    "C-lang",
    "C language",
    "C-kieli",
    "!C tai CE",
    "!C kortti",
    "!C-kortti",
    "!osio C",
    "!C-Level",
    "!C-level",
    "!C-suite",
    "!C-panel",
    "!OVTES C",
    "!C, Chemical",
    "!2 C",
    "!5 C",
    "!interview C",
  ],
  [
    "Golang",
    "Go-lang",
    "Golangiin",
    "Go ohjelmistokehittäjä",
    "!go live",
    "!go to",
    "!go-to",
    "!go ahead",
    "!go with",
    "!go for",
  ],
  "Rust",
  "Scala",
  "Kotlin",
  ["Swift", "!swiftly"],
  "Objective-C",
  "Perl",
  "Haskell",
  "Clojure",
  "Erlang",
  "Elixir",
  "Dart",
  "Lua",
  "R",
  ["Bash", "Shell", "sh", "zsh"],
  "PowerShell",
  ["Assembly", "ASM"],
  "MATLAB",
  ["Visual Basic", "VBA"],
  "COBOL",
  "Fortran",
  "Lisp",
  "Pascal",
  "Delphi",
  "LabVIEW",
  "Ada",
  "PL/SQL",
  "Prolog",
  // Markup / Query / Data description languages often treated as languages in JDs
  ["SQL", "Structured Query Language"],
  ["HTML", "HTML5"],
  ["CSS", "CSS3", "SCSS", "Sass", "Less"],
  ["JSON", "JSON5"],
  ["YAML", "YML"],
  // Modern / niche
  "Julia",
  "Groovy",
  "ABAP",
  ["Apex", "Salesforce Apex"],
  "Solidity",
  "WebAssembly",
  "Zig",
  "Nim",
  "V",
];

export const frameworks = [
  ["Node", "Node.js", "NodeJS"],
  ["React", "React.js", "ReactJS"],
  ["NextJS", "Next.js", "Next"],
  ["Remix", "Remix.run"],
  ["SolidJS"],
  ["Astro", "Astro.js"],
  ["Qwik", "Qwik.js"],
  ["Preact", "Preact.js"],
  ["Vue", "Vue.js", "VueJS"],
  ["Nuxt", "Nuxt.js", "NuxtJS"],
  ["Angular", "Angular.js", "AngularJS"],
  ["Svelte", "Svelte.js", "SvelteJS"],
  ["Gatsby", "Gatsby.js", "GatsbyJS"],
  ["Ember", "Ember.js", "EmberJS"],
  ["Express", "ExpressJS", "Express.js"],
  ["NestJS", "Nest"],
  ["Koa", "Koa.js"],
  ["Hapi", "Hapi.js"],
  ["Fastify", "Fastify.js"],
  ["tRPC", "trpc"],
  ["Redux", "Redux Toolkit"],
  "MobX",
  "Zustand",
  "RxJS",
  ["Electron", "Electron.js", "ElectronJS"],
  ["Flutter", "Flutter.js", "FlutterJS"],
  ["React Native", "ReactNative", "React-Native"],
  ["Ionic", "Ionic.js", "IonicJS"],
  ["Bootstrap", "Bootstrap.js", "BootstrapJS"],
  ["Tailwind", "TailwindCSS", "Tailwind.js", "TailwindJS"],
  ["Material UI", "MUI", "Material-UI"],
  ["Chakra UI", "Chakra"],
  ["Framer Motion", "Framer"],
  ["Jquery", "jQuery"],
  // Python web
  "Django",
  ["Django REST Framework", "DRF"],
  "Flask",
  "FastAPI",
  "Tornado",
  // Ruby & PHP
  ["Ruby on Rails", "Rails"],
  ["Laravel", "Lumen"],
  "Symfony",
  "CodeIgniter",
  "Yii",
  "CakePHP",
  // Java & JVM
  ["Spring", "Spring Boot"],
  "Hibernate",
  "Micronaut",
  "Quarkus",
  "Struts",
  ["Play Framework"],
  "Ktor",
  // .NET
  ["ASP.NET", "ASP.NET Core", "ASP"],
  ".NET",
  // Data / AI
  ["TensorFlow", "Tensor Flow", "Tensor-Flow"],
  ["PyTorch", "Py Torch", "Py-Torch"],
  "Keras",
  ["scikit-learn", "sklearn"],
  "XGBoost",
  "LightGBM",
  "CatBoost",
  ["OpenCV", "cv2"],
  ["spaCy", "Spacy"],
  ["Hugging Face", "Transformers"],
  ["JAX", "Flax"],
  ["LangChain", "Lang Chain"],
  ["LlamaIndex", "Llama Index", "GPT Index"],
  ["Pandas", "Pandas.js", "PandasJS"],
  ["NumPy", "NumPy.js", "NumPyJS"],
  ["Apache Spark", "Spark"],
  "Hadoop",
  ["Airflow", "Apache Airflow"],
  "dbt",
  ["Kafka", "Apache Kafka"],
  ["Flink", "Apache Flink"],
  ["Beam", "Apache Beam"],
  // CMS / e‑com
  ["WordPress", "Word Press", "Word-Press"],
  ["Shopify", "Shopify.js", "ShopifyJS"],
  ["WooCommerce", "Woo Commerce", "Woo-Commerce"],
  // Notebooks / Robotics / Misc
  ["Jupyter Notebook", "JupyterNotebook", "Jupyter"],
  ["ROS", "Robot Operating System"],
  ["Unity", "Unity3D"],
  ["Unreal Engine", "UnrealEngine", "Unreal-Engine"],
];

export const databases = [
  [
    "Relational databases",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MariaDB",
    "MS-SQL",
    "Microsoft SQL Server",
    "Oracle Database",
  ],
  [
    "NoSQL databases",
    "NoSQL",
    "no-SQL",
    "MongoDB",
    "DynamoDB",
    "Redis",
    "Cassandra",
    "Neo4j",
    "Couchbase",
    "CouchDB",
    "Elasticsearch",
    "OpenSearch",
    "ArangoDB",
  ],
  [
    "Vector databases",
    "vectorDB",
    "vector database",
    "vector-database",
    "vektori tietokannat",
    "vektori tietokanta",
    "Pinecone",
    "Weaviate",
    "Milvus",
    "Qdrant",
    "Chroma",
  ],
  "Snowflake",
  ["Amazon Redshift", "Redshift"],
  ["Google BigQuery", "BigQuery"],
  "ClickHouse",
  "TimescaleDB",
  "InfluxDB",
  "QuestDB",
  "Neo4j",
  "JanusGraph",
  "CockroachDB",
  "TiDB",
  "Amazon Aurora",
];

export const cloud = [
  ["AWS", "Amazon Web Services", "S3", "S3 Bucket", "EC2", "Lambda", "RDS", "ECS", "EKS", "CloudFront"],
  ["Azure", "Microsoft Azure", "AKS", "Functions", "App Service"],
  ["Google Cloud", "GCP", "GKE", "Cloud Run", "App Engine", "Pub/Sub"],
  "Firebase",
  "Cloudflare",
  "Vercel",
  "Netlify",
  "Heroku",
  "Digital Ocean",
  "Linode",
  "Rackspace",
  "IBM Cloud",
  "Alibaba Cloud",
  "Oracle Cloud",
  "VMware Cloud",
  "Red Hat OpenShift",
  "Salesforce Cloud",
  "SAP Cloud",
  ["Public cloud", "Public-cloud"],
  ["Private cloud", "Private-cloud", "on premise", "on-premise", "on‑prem", "onprem"],
  "Hybrid cloud",
  ["Cloud", "Pilvi", "pilvipalveluiden", "pilvipalvelu"],
  ["Serverless", "Function as a Service", "FaaS"],
];

export const devops = [
  // VCS & Collaboration
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "Bitbucket",
  // CI/CD
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitLab CI/CD",
  "Azure DevOps",
  "Argo CD",
  "Spinnaker",
  "Harness",
  // IaC & Config
  "Terraform",
  "Pulumi",
  "AWS CloudFormation",
  "Ansible",
  "Chef",
  "Puppet",
  "Vagrant",
  "Helm",
  // Containers & Orchestration & Service Mesh
  "Docker",
  "Kubernetes",
  "Istio",
  "Linkerd",
  "Consul",
  // Observability
  "Prometheus",
  "Grafana",
  "Loki",
  "OpenTelemetry",
  "Datadog",
  "New Relic",
  "Sentry",
  "PagerDuty",
  "Opsgenie",
  // Logging & Search
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Splunk",
  "Graylog",
  // Web servers & proxies
  "Nginx",
  "Apache HTTPD",
  // Artifact & Code Quality
  "SonarQube",
  "Artifactory",
  "Nexus Repository",
  "Packer",
  // Agile / Project tools
  "Agile",
  "Scrum",
  "Kanban",
  "CI/CD",
  "DevOps",
  "Pipeline",
  "Taiga",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  // Build systems / test
  "Maven",
  "Gradle",
  "Bazel",
  "Nx",
  "Turborepo",
  "Jest",
  "Mocha",
  "Cypress",
  "Playwright",
  "Selenium",
  "JUnit",
  "pytest",
  "RSpec",
  "PHPUnit",
  "Cucumber",
];

export const dataScience = [
  ["Machine Learning", "Koneoppiminen", "Koneoppimisen", "ML"],
  ["Deep Learning", "Syväoppiminen", "Syväoppimisen"],
  ["Reinforcement learning", "Vahvistusoppiminen", "Vahvistusoppimisen", "RL"],
  "Big Data",
  ["Data Analysis", "Data Analyst", "Data Analytics", "Data-analyysi", "Data-analyytikko", "Data-analytiikka"],
  ["Data Visualization", "Data Visualisation", "Data Visualisointi", "Data-visualisointi"],
  ["Data Engineering", "Data Engineer", "Data Pipelines", "ETL"],
  ["Natural Language Processing", "NLP", "Luonnollisen kielen käsittely"],
  ["Computer Vision", "Konenäkö"],
  ["Statistics", "Statistical Analysis", "Tilastotiede", "Tilastollinen analyysi"],
  ["Business Intelligence", "BI", "Liiketoimintatieto"],
  ["Data Warehousing", "Data Warehouse", "Datan varastointi"],
  ["Data Modeling", "Data Modelling", "Datan mallintaminen", "Data Modeler"],
  ["Data Mining", "Datan kaivaminen", "Data Miner"],
  ["Data Management", "Datan hallinta"],
  ["Artificial Intelligence", "Tekoäly"],
  // Libraries / platforms
  ["scikit-learn", "sklearn"],
  "XGBoost",
  "LightGBM",
  "CatBoost",
  ["Hugging Face", "Transformers"],
  ["LangChain", "Lang Chain"],
  ["LlamaIndex", "GPT Index"],
  ["RAG", "Retrieval-Augmented Generation"],
  ["OpenCV", "cv2"],
  ["spaCy", "Spacy"],
  ["MLflow", "ML Flow"],
  "Kubeflow",
  "Vertex AI",
  "SageMaker",
  ["Pandas", "NumPy"],
];

export const softSkills = [
  ["Communication", "Viestintä", "kommunikointi", "kommunikaatio"],
  ["Teamwork", "Tiimityöskentely", "Collaboration", "Yhteistyö", "tiimityö", "team player"],
  ["Problem Solving", "Problem-solving", "Ongelmanratkaisu", "critical thinking", "problem solver"],
  ["Innovation", "Creativity", "Creative", "Luovuus", "Innova", "luova"],
  ["Time management", "Ajanhallinta", "prioritize", "priorisoi"],
  ["Adaptability", "Mukautuvuus", "sopeutuvuus", "sopeutumis"],
  ["Flexibility", "Joustavuus"],
  ["Leadership", "Johtajuus", "johtaminen", "johtaa", "tiimin vetäjä", "Team leading", "team leader"],
  ["Mentoring", "Coaching", "mentorointi"],
  ["Ownership", "omistajuus"],
  ["Documentation", "dokumentointi"],
  ["Presentation", "esitystaidot", "presentointi"],
  ["Stakeholder management", "sidosryhmätyö"],
  ["Negotiation", "neuvottelutaidot"],
  ["People skills", "ihmisläheinen"],
  ["Work ethic", "Työmoraali"],
  ["Dedication", "Sitoutuminen"],
  ["Reliability", "Luotettavuus"],
  ["Optimism", "Positiivinen asenne", "Positive attitude", "Optimismi", "positiivinen", "positiivisuus"],
  ["Customer Service", "asiakaspalvelu", "asiakaspalveluhenki", "asiakaslähtöi"],
  ["Motivation", "motivaatio", "motivoitunut"],
  ["Empathy", "Empatia"],
  ["Patience", "Kärsivällisyys", "kärsivällinen"],
  ["Accountability", "Vastuullisuus", "vastuullinen"],
  ["Self-directed", "itsenäinen", "itseohjautuva"],
  ["Curiosity", "utelias"],
  ["Pressure Tolerance", "paineensietokyky", "paineensieto", "under pressure", "paineen alla"],
  ["Feedback", "palautetta", "palaute", "palautteen"],
];

export const positions = [
  ["Full Stack", "Full-Stack", "Fullstack"],
  ["Front End", "Front-End", "Frontend", "frontti"],
  ["Back End", "Back-End", "Backend", "bäkkäri"],
  ["Consultant", "Consulting", "Konsultti", "Konsultointi"],
  [
    "Software Developer",
    "Software Engineer",
    "SW Developer",
    "Ohjelmistokehittäjä",
    "Ohjelmoija",
    "Koodari",
    "Koodaaja",
    "Kehittäjä",
    "Developer",
  ],
  ["Software Architect", "Software Architecture", "Arkkitehti", "Solutions Architect", "Solution Architect"],
  ["Cloud Architect", "Pilviarkkitehti"],
  ["Systems Architect", "Järjestelmäarkkitehti"],
  ["Web Developer", "Web Development", "web-kehitys", "web-kehittäjä"],
  ["Mobile Developer", "Mobile Development", "mobiilikehitys", "mobiilikehittäjä"],
  ["Platform Engineer", "Platform Engineering"],
  ["Site Reliability Engineer", "SRE"],
  ["DevOps Engineer", "DevOps Developer", "CI-/DevOps"],
  ["Data Engineer", "Data Engineering"],
  ["Data Scientist", "Data Science"],
  ["Data Analyst", "Data-analyytikko"],
  ["Business Intelligence Developer", "BI Developer"],
  ["Machine Learning Engineer", "Machine Learning", "ML Engineer"],
  ["MLOps Engineer", "ML Ops Engineer"],
  ["Cloud Engineer", "Cloud Engineering"],
  ["Embedded", "Sulautetut", "Embedded Engineer"],
  [
    "Cyber Security",
    "Security Engineering",
    "Security Engineer",
    "Tietoturva",
    "Tietoturvakonsultti",
    "tietoturvan",
    "Security Analyst",
    "SOC Analyst",
  ],
  ["Penetration Tester", "Pentester", "Penetraatiotestaaja"],
  ["Network Engineer", "Verkkoinsinööri"],
  ["QA Engineer", "QA Engineering", "Test Engineer", "Test Engineering", "Testauksen"],
  ["Test Automation", "Testausautomaatio"],
  ["UX Designer", "UX Design", "Käytettävyys", "Saavutettavuus"],
  ["UI Designer", "UI Design", "Käyttöliittymäsuunnittelija", "Käyttöliittymäsuunnittelu"],
  ["Product Designer", "Tuotesuunnittelija"],
  ["Designer", "Suunnittelija"],
  ["System Administrator", "System Administration", "Järjestelmänvalvoja", "järjestelmävastaava"],
  ["System Specialist", "Järjestelmäasiantuntija"],
  ["Product Manager", "Product Management", "Product Owner"],
  ["Project Manager", "Project Management"],
  ["Business Analyst", "Business Analysis"],
  ["Scrum Master"],
  ["AI Engineer", "AI Programmer", "AI Developer", "Tekoäly"],
  ["Blockchain Engineer", "Blockchain Developer", "Lohkoketju"],
  ["Game Developer", "Game Development", "Pelikehittäjä", "Pelikehitys"],
  ["Game Designer", "Game Design", "Pelisuunnittelija", "Pelisuunnittelu"],
  ["Teacher / Professor", "Teacher", "Opettaja", "Professori"],
  ["Researcher", "Tutkija"],
  ["Salesman", "Myynti", "Myyjä"],
];

export const seniority = [
  ["Intern", "Trainee", "Harjoittelija", "harjoittelu", "digistar", "kesätyö"],
  ["Junior", "Juniori", "entry", "!senior"],
  ["Mid-level", "Mid", "Regular", "Intermediate"],
  ["Senior", "Seniori", "senior"],
  [
    "Lead",
    "Tiimin vetäjä",
    "Johtava",
    "Johtaja",
    "Team Lead",
    "Architect",
    "Arkkitehti",
    "Staff",
    "Staff Engineer",
    "Principal",
    "Head",
    "Päälikkö",
  ],
  ["Director", "Executive", "Vice President", "VP", "Johtaja", "direktör"],
  [
    "Chief",
    "C-level",
    "CIO",
    "CISO",
    "Toimitusjohtaja",
    "Teknologiajohtaja",
    "Tiedonhallintajohtaja",
    "Tietoturvajohtaja",
    "Verkställande direktör",
  ],
];

// City names (some grouped with common Finnish inflected variants / genitives)
export const finnishCities = [
  ["Helsinki", "Helsingissä", "Helsingin"],
  "Espoo",
  "Tampere",
  "Vantaa",
  "Oulu",
  "Turku",
  "Jyväskylä",
  "Lahti",
  "Kuopio",
  "Kouvola",
  "Pori",
  "Joensuu",
  "Lappeenranta",
  "Hämeenlinna",
  "Vaasa",
  "Rovaniemi",
  "Seinäjoki",
  "Mikkeli",
  "Kotka",
  "Salo",
  "Porvoo",
  "Kokkola",
  "Lohja",
  "Hyvinkää",
  "Nurmijärvi",
  "Järvenpää",
  "Rauma",
  "Kirkkonummi",
  "Tuusula",
  "Kajaani",
  "Kalajoki",
  "Kemi",
  "Riihimäki",
  "Savonlinna",
  "Kaarina",
  "Kerava",
  "Ylöjärvi",
  "Imatra",
  "Sastamala",
];
